version: '3.4'

services:
  app1: &app
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    hostname: app1
    #ports: # Conferindo o backend do host
    #  - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production
      - PORT=8080
      - PINO_LOG_LEVEL=debug
      - REQ_TIMEOUT=2000
      - CLUSTER=true
      - CLUSTER_WORKERS=5
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.6GB'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=production
      - PORT=3000
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.6GB'

  app2:
    <<: *app
    hostname: app2

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    ports:
      - "9999:9999"

